<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

//Contenido del módulo
function hola_mundo_help($route_name){
    if($route_name == 'help.page.hola_mundo'){
        return '<p>¡Hola mundo!</p>';
    }
}


//Hook que modifica una vista
function hola_mundo_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
    
    if ($view->id() == 'blog') {
        $query->addWhere('status', 'node_field_data.status', 1);
    }
}







