# Schema for the configuration files of the Breadcrumb extra field module.

breadcrumb_extra_field.settings:
  type: config_object
  label: 'Breadcrumb extra field settings'
  mapping:
    breadcrumb_extra_field_admin:
      type: sequence
      label: 'Entity types'
      sequence:
        type: sequence
        label: 'Entity bundles'
        sequence:
          type: string
          label: 'Bundle'
