block.settings.fractionslider_configurable_text:
  type: block_settings
  label: 'fractionslider block configuration'
  mapping:
    fractionslider_string:
      type: text
      label: 'Block contents'
